// <auto-generated />
namespace DemoApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class abc5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(abc5));
        
        string IMigrationMetadata.Id
        {
            get { return "202210260526354_abc5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
